"""empty message

Revision ID: 4321181b2dfb
Revises:
Create Date: 2022-12-01 15:30:49.955170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4321181b2dfb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("tx_id", sa.String(), nullable=False),
        sa.Column("tx_result", sa.String(), nullable=True),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("signer", sa.String(), nullable=False),
        sa.Column("nonce", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("tx_id"),
        sa.UniqueConstraint("signer", "nonce"),
    )
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transaction_signer"), ["signer"], unique=False
        )

    op.create_table(
        "world_boss_reward",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raid_id", sa.Integer(), nullable=False),
        sa.Column("avatar_address", sa.String(), nullable=False),
        sa.Column("agent_address", sa.String(), nullable=False),
        sa.Column("ranking", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raid_id", "avatar_address", "agent_address"),
        sa.UniqueConstraint("raid_id", "ranking"),
    )
    with op.batch_alter_table("world_boss_reward", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_world_boss_reward_agent_address"),
            ["agent_address"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_world_boss_reward_avatar_address"),
            ["avatar_address"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_world_boss_reward_raid_id"), ["raid_id"], unique=False
        )

    op.create_table(
        "world_boss_reward_amount",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.Column("tx_id", sa.String(), nullable=False),
        sa.Column("reward_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reward_id"],
            ["world_boss_reward.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tx_id"],
            ["transaction.tx_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("world_boss_reward_amount")
    with op.batch_alter_table("world_boss_reward", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_world_boss_reward_raid_id"))
        batch_op.drop_index(batch_op.f("ix_world_boss_reward_avatar_address"))
        batch_op.drop_index(batch_op.f("ix_world_boss_reward_agent_address"))

    op.drop_table("world_boss_reward")
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_signer"))

    op.drop_table("transaction")
    # ### end Alembic commands ###
