repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [
            types-redis==4.3.21.6,
            types-requests==2.28.11.5,
        ]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [world_boss, tests]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
