name: run test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        id: cp310
        with:
          python-version: "3.10"
          cache: 'poetry'
      - run: echo '${{ steps.cp310.outputs.python-version }}'
      - run: poetry install
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Install dependencies
        run: |
          poetry install
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 12-alpine
          postgres_password: ${{ secrets.DB_PASS }}
      - name: actions-setup-redis
        uses: shogo82148/actions-setup-redis@v1.19.0
        with:
          redis-version: 4
          auto-start: false
      - name: Test with pytest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
        run: |
          poetry run pytest --redis-exec=$(which redis-server) --cov world_boss --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
